### ISSUE TITLE
Add the info of the listened music in the reply msg

### ISSUE THREAD

**Issue by claudiazi** [gabrieljaegerde/spotify_telegram_bot#15]
If a sender sent more than one song and multiple songs were in the queue. After the admin listened to one of these songs, the sender should get the location msg with the name of the song, otherwise, the sender will be confused 🤷‍♀️

**Comment by MrTrollionaire** [comment]
not fair, i solved this issue in the wrong repository :-( 

https://github.com/gabrieljaegerde/send_me_songs_bot/issues/2

**Comment by gabrieljaegerde** [comment]
@MrTrollionaire made a small change to your code from the other repo and implemented fix. Thanks
